import test from 'node:test';
import assert from 'node:assert/strict';
import { createBackendClient, getOrCreateIdentity } from '../src/backend-client.js';
import { createDemoController } from '../src/demo-controller.js';
import { sha256 } from '../src/identity.js';
import { bindRerunEvents, startInitialRun } from '../src/integration-port.js';

const health = { ok: true, api: { current: 1, supported: [1] }, capabilities: { records: true, optimisticRevision: true } };
async function waitUntil(predicate, message = '等待异步 seam 超时') { for (let index = 0; index < 100 && !predicate(); index += 1) await new Promise(resolve => setImmediate(resolve)); assert.ok(predicate(), message); }

test('事件接线会 invalidate 后重跑，异步错误脱敏且不产生未处理 rejection', async () => {
  const handlers = {}; const logs = []; let invalidates = 0; let runs = 0;
  const controller = { invalidate: () => invalidates++, runDemo: async () => { runs++; throw new Error('secret response /absolute/path'); } };
  bindRerunEvents({ eventSource: { on: (name, handler) => { handlers[name] = handler; } }, eventTypes: { CHAT_CHANGED: 'chat', PERSONA_CHANGED: 'persona' }, controller, logger: { warn: message => logs.push(message) } });
  handlers.chat(); handlers.persona(); await new Promise(resolve => setImmediate(resolve)); assert.equal(invalidates, 2); assert.equal(runs, 2); assert.deepEqual(logs, ['[qianqianjie-demo] 事件重跑失败', '[qianqianjie-demo] 事件重跑失败']);
});
test('初始运行 seam 只调用一次并吞掉错误', async () => { let runs = 0; const logs = []; startInitialRun({ runDemo: async () => { runs++; throw new Error('sensitive'); } }, { warn: x => logs.push(x) }); await new Promise(resolve => setImmediate(resolve)); assert.equal(runs, 1); assert.deepEqual(logs, ['[qianqianjie-demo] 初始运行失败']); });
function harness() {
  const db = new Map(); const calls = []; const fetchImpl = async (url, options = {}) => {
    calls.push({ url, options }); const parts = url.split('/'); const key = parts.slice(-3).join('/');
    if (url.endsWith('/v1/health')) return { ok: true, status: 200, json: async () => health };
    if (options.method === 'PUT') { const body = JSON.parse(options.body); if (db.has(key) && body.expectedRevision === 0) return { ok: false, status: 409, json: async () => ({}) }; const record = { revision: 1, data: body.data }; db.set(key, record); return { ok: true, status: 200, json: async () => record }; }
    if (!db.has(key)) return { ok: false, status: 404, json: async () => ({}) }; return { ok: true, status: 200, json: async () => db.get(key) };
  }; return { db, calls, client: createBackendClient({ fetchImpl, headers: () => ({ Authorization: 'test' }) }) };
}
function context() { return { characterId: 0, groupId: null, chatId: 'chat-1', characters: [{ avatar: 'char.png' }], userAvatar: 'me.png', chatMetadata: {}, saveMetadata: async () => {} }; }

test('首次创建、刷新恢复且不重写探针', async () => {
  const h = harness(); const ctx = context(); const controller = createDemoController({ client: h.client, contextProvider: () => ctx, toast: { success() {}, warning() {} } });
  const first = await controller.runDemo(); assert.equal(first.status, 'created'); const size = h.calls.length;
  const second = await controller.runDemo(); assert.equal(second.status, 'restored'); assert.equal(h.calls.length, size + 4); assert.match(ctx.chatMetadata.qianqianjie.chatId, /^[0-9a-f-]{36}$/); assert.equal([...h.db.values()].find(x => x.data?.kind === 'chat-demo-profile').data.chatId, ctx.chatMetadata.qianqianjie.chatId);
});
test('404/409 竞争只返回一个已有记录', async () => { const h = harness(); const a = await getOrCreateIdentity(h.client, 'identity-cards', 'same', { x: 1 }); assert.equal(a.created, true); const b = await getOrCreateIdentity(h.client, 'identity-cards', 'same', { x: 2 }); assert.equal(b.created, false); assert.equal(b.record.data.x, 1); });
test('群聊或缺身份安全停止，不请求后端', async () => { const h = harness(); const ctx = context(); ctx.groupId = 'g'; const c = createDemoController({ client: h.client, contextProvider: () => ctx }); const result = await c.runDemo(); assert.equal(result.status, 'stopped'); assert.equal(h.calls.length, 0); });
test('聊天元数据保存失败时不落后端', async () => { const h = harness(); const ctx = context(); ctx.saveMetadata = async () => { throw new Error('metadata failed'); }; const c = createDemoController({ client: h.client, contextProvider: () => ctx }); await assert.rejects(c.runDemo(), /metadata failed/); assert.equal(h.calls.length, 1); assert.equal(h.calls[0].url, '/api/plugins/st-bainiaodata/v1/health'); });
test('并发运行共享在途保存：首个失败时后续不写后端', async () => { const h = harness(); const ctx = context(); let release; let rejectSave; ctx.saveMetadata = () => new Promise((resolve, reject) => { release = resolve; rejectSave = reject; }); const c = createDemoController({ client: h.client, contextProvider: () => ctx }); const first = c.runDemo(); for (let i = 0; i < 20 && !rejectSave; i++) await new Promise(resolve => setImmediate(resolve)); const second = c.runDemo(); rejectSave(new Error('save failed')); release?.(); const firstError = await first.then(() => null, error => error); assert.ok(firstError); assert.equal((await second).status, 'stopped'); assert.equal([...h.calls].filter(x => x.options.method === 'PUT').length, 0); assert.equal(ctx.chatMetadata.qianqianjie, undefined); });
test('元数据失败后可重试并复用已保存 UUID', async () => { const h = harness(); const ctx = context(); let failures = 1; ctx.saveMetadata = async () => { if (failures--) throw new Error('once'); }; const c = createDemoController({ client: h.client, contextProvider: () => ctx }); await assert.rejects(c.runDemo()); assert.equal(ctx.chatMetadata.qianqianjie, undefined); await c.runDemo(); const uuid = ctx.chatMetadata.qianqianjie.chatId; await c.runDemo(); assert.equal(ctx.chatMetadata.qianqianjie.chatId, uuid); });
test('Persona 不匹配只读告警且不创建新身份', async () => { const h = harness(); const ctx = context(); const controller = createDemoController({ client: h.client, contextProvider: () => ctx, toast: { success() {}, warning: message => assert.match(message, /不一致/) } }); await controller.runDemo(); const before = h.db.size; ctx.userAvatar = 'other.png'; const result = await controller.runDemo(); assert.equal(result.status, 'mismatch'); assert.equal(h.db.size, before); });
test('chat 404→第二 GET 404→PUT 409→GET 异 Persona 时不读写两类身份', async () => {
  const ctx = context(); let chatGets = 0; let identityGets = 0; let identityPuts = 0; const client = {
    health: async () => ({ ok: true }),
    get: async (collection) => { if (collection === 'chat-meta') { chatGets++; if (chatGets === 1) { const e = new Error('404'); e.status = 404; throw e; } return { data: { chatId: ctx.chatMetadata.qianqianjie.chatId, personaId: 'avatar-other', source: { characterAvatar: 'char.png', personaAvatar: 'other.png' } } }; } identityGets++; return { data: {} }; },
    put: async (collection) => { if (collection === 'chat-meta') { const e = new Error('409'); e.status = 409; throw e; } identityPuts++; return { data: {} }; },
  }; const c = createDemoController({ client, contextProvider: () => ctx, toast: { warning() {} } }); const result = await c.runDemo(); assert.equal(result.status, 'mismatch');
  assert.equal(identityGets, 0); assert.equal(identityPuts, 0);
});
test('已有 chat 档案缺 personaId 时 fail-closed 且不读写身份', async () => { const ctx = context(); let identityGets = 0; let identityPuts = 0; const client = { health: async () => ({ ok: true }), get: async collection => collection === 'chat-meta' ? { data: { chatId: ctx.chatMetadata.qianqianjie.chatId } } : (identityGets++, { data: {} }), put: async () => (identityPuts++, { data: {} }) }; const result = await createDemoController({ client, contextProvider: () => ctx, toast: { warning() {} } }).runDemo(); assert.equal(result.status, 'mismatch'); assert.equal(identityGets, 0); assert.equal(identityPuts, 0); });
test('身份 PUT 进行中失效时不启动后续 Persona 写入', async () => { const h = harness(); const ctx = context(); let release; let personaPuts = 0; const client = { health: h.client.health, get: async () => { const e = new Error('404'); e.status = 404; throw e; }, put: async (collection, key, data) => { if (collection === 'chat-meta') return { revision: 1, data }; if (collection === 'identity-cards') return new Promise(resolve => { release = () => resolve({ revision: 1, data }); }); personaPuts++; return { revision: 1, data }; } }; const c = createDemoController({ client, contextProvider: () => ctx }); const p = c.runDemo(); await waitUntil(() => typeof release === 'function'); c.invalidate(); release(); assert.equal((await p).status, 'stale'); assert.equal(personaPuts, 0); });
test('legacy 三记录懒迁移到独立 UUID，第二次不再写', async () => {
  const ctx = context(); ctx.chatMetadata.qianqianjie = { schemaVersion: 1, chatId: '123e4567-e89b-12d3-a456-426614174000' }; const cardRecordId = `avatar-${await sha256('char.png')}`; const personaRecordId = `avatar-${await sha256('me.png')}`; const calls = []; const records = { 'chat-meta': { revision: 2, data: { schemaVersion: 1, kind: 'chat-demo-profile', chatId: ctx.chatMetadata.qianqiejjie?.chatId ?? ctx.chatMetadata.qianqianjie.chatId, cardId: cardRecordId, personaId: personaRecordId, demoProbe: 'qianqianjie-demo-v1' } }, 'identity-cards': { revision: 3, data: { schemaVersion: 1, kind: 'identity-card', avatar: 'char.png' } }, 'identity-personas': { revision: 4, data: { schemaVersion: 1, kind: 'identity-persona', avatar: 'me.png' } } };
  const client = { health: async () => ({ ok: true }), get: async (collection, id) => { calls.push(['get', collection, id]); if (collection === 'chat-meta') return records['chat-meta']; if (collection === 'identity-cards') return records['identity-cards']; return records['identity-personas']; }, put: async (collection, id, data, revision) => { calls.push(['put', collection, id, data, revision]); records[collection] = { revision: revision + 1, data }; return records[collection]; } };
  const c = createDemoController({ client, contextProvider: () => ctx }); const first = await c.runDemo(); assert.equal(first.status, 'migrated'); assert.match(records['identity-cards'].data.identityId, /^[0-9a-f-]{36}$/); assert.match(records['identity-personas'].data.identityId, /^[0-9a-f-]{36}$/); assert.equal(records['chat-meta'].data.cardId, records['identity-cards'].data.identityId); assert.equal(records['chat-meta'].data.personaId, records['identity-personas'].data.identityId); const writes = calls.filter(x => x[0] === 'put'); assert.deepEqual(writes.map(x => x[1]), ['chat-meta', 'identity-cards', 'identity-personas']); assert.equal(writes[0][4], 2); assert.equal(writes[1][4], 3); assert.equal(writes[2][4], 4); const count = writes.length; await c.runDemo(); assert.equal(calls.filter(x => x[0] === 'put').length, count);
});
test('旧异步运行失效且错误不泄漏响应正文', async () => { let release; const h = harness(); const slow = async (...args) => { await new Promise(resolve => { release = resolve; }); return h.client; }; const ctx = context(); const c = createDemoController({ client: { health: slow }, contextProvider: () => ctx }); const pending = c.runDemo(); await waitUntil(() => typeof release === 'function'); c.invalidate(); release(); const result = await pending; assert.equal(result.status, 'stale'); const error = new Error('后端请求失败（HTTP 500）'); assert.doesNotMatch(error.message, /secret|root|payload/i); });
